### ISSUE TITLE
Agglutinative morphology of Arabic

### ISSUE THREAD

**Issue by yassmine-lam** [aub-mind/arabert#120]
Hi 
I have a question about the effectiveness of AraBERT in handling Agglutinative morphology of Arabic in tasks such as named entity recognitioncan the model handle the different format of writing a word e.g مسجد  مسجدا مسجدنا 
Also how it can handle the omission of diacritics in MSA

Thank u

**Comment by WissamAntoun** [comment]
Hey,

Diacritics won't matter with our models, since they get removed by the preprocessor.

As for the Agglutinative morphology of Arabic, well it depends.
If you are using AraBERTv02 or AraELECTRA, the tokenizer will split the words as follows: `['مسجد', 'مسجدا', 'مسجد', '##نا']` , here you can see that from the model's perspective the token `مسجد` and `مسجدا` are two different tokens, the model should have similar representation for both but it is not guaranteed. This is a limitation of the tokenization scheme that we used ( writing mistakes also have similar behavior, if not worse).

Now in the case of `مسجدنا`, the tokenizer split the word into `[مسجد,##نا]` , and in NER we usually consider the label of the first token only. Which in this case worked out well in this case. But in other cases like when we have `ال` at the start of the word will cause some degradation.

Hopefully, I answered your question.

**Comment by yassmine-lam** [comment]
Hi,

thank u very much for the detailed answer 
another question plz u reported a high result of NER task using AraBERT
how did u handled the case of having ال at the start of entities? 

thank u in advance

**Comment by WissamAntoun** [comment]
In the case of the models without pre-segmentation we didn't do anything extra.

With the models with pre-segmentation, I tried to put the NER label on a non-prefix token, but it didn't improve the results. So we left it as it is

**Comment by yassmine-lam** [comment]
ok thank u very much for ur clarification
