### ISSUE TITLE
Issues with GPT2-mega 'probability tensor contains either 'inf',  'nan' or element <0'

### ISSUE THREAD

**Issue by asyraf1997** [aub-mind/arabert#149]
Issues with GPT2-mega 'probability tensor contains either 'inf',  'nan' or element <0'

from transformers import GPT2TokenizerFast, pipeline

from arabert.aragpt2.grover.modeling_gpt2 import GPT2LMHeadModel

MODEL_NAME='tmp/aragpt2-mega'

model = GPT2LMHeadModel.from_pretrained(MODEL_NAME)
tokenizer = GPT2TokenizerFast.from_pretrained(MODEL_NAME)
generation_pipeline = pipeline("text-generation", model=model, tokenizer=tokenizer) 

output = generation_pipeline( text,
            pad_token_id=tokenizer.eos_token_id,
            max_length=500,
            min_length=250,
            top_k=40,
            temperature=0.75,
            repetition_penalty=3.0,)

transformers==4.2.1
torch==1.9.1
tokenizers==0.9.4

Error Occurs : 
Invalid lambda response received: Invalid API Gateway Response Keys: {'errorMessage', 'stackTrace', 'errorType'} in {'errorMessage': 'probability tensor contains either `inf`, `nan` or e
lement < 0', 'errorType': 'RuntimeError', 'stackTrace': ['  File "/var/task/app.py", line 23, in lambda_handler\n    results_Input, results_Output = helpers.get_textGenerationInputs(keyw
ords, proxy, location, language)\n', '  File "/var/task/helpers.py", line 610, in get_textGenerationInputs\n    result_completion = list(map(get_GenerationAraGpt2Mega, list_togen))\n', '
  File "/var/task/helpers.py", line 580, in get_GenerationAraGpt2Mega\n    no_repeat_ngram_size = 3)[0][\'generated_text\']\n', '  File "/var/task/transformers/pipelines/text_generation.
py", line 141, in __call__\n    output_sequences = self.model.generate(input_ids=input_ids, **generate_kwargs)  # BS x SL\n', '  File "/var/task/torch/autograd/grad_mode.py", line 28, in
 decorate_context\n    return func(*args, **kwargs)\n', '  File "/var/task/transformers/generation_utils.py", line 996, in generate\n    **model_kwargs,\n', '  File "/var/task/transforme
rs/generation_utils.py", line 1884, in beam_sample\n    next_tokens = torch.multinomial(probs, num_samples=2 * num_beams)\n']}

**Comment by WissamAntoun** [comment]
I was able to successfully replicate the issue. It seems the issue occurs when the temperature value is lower than ~0.9, this threshold may vary since it depends on the prompt used.

Setting the temperature to 1 (which practically disables temp. sampling) is the safe choice unless temperature sampling is a must in your case.

I will be updating the modeling_gpt2.py code to better match the one in transformers v4.2.1, but it won't solve the problem. I'm also not sure if the problem is solved in the newer version of the library, since the error occurs in the generation_utils.py file.

Right now I don't have the time-bandwidth to upgrade the modeling_gpt2.py to be compatible with transformers 4.16.2, since there is a lot of changes.
