### ISSUE TITLE
Is pretraining data available?

### ISSUE THREAD

**Issue by ahmednasserswe** [aub-mind/arabert#16]
Hello! 

I am currently working on training Electra for Arabic. I wonder if you already have the pretraining data saved somewhere that you could share with me. Would be even better if it is already preprocessed into tfrecords! I am doing it as opensource.

**Comment by WissamAntoun** [comment]
Hey ahmed,

The data that we used is currently not stored on the cloud since it was costing us a lot. Also, you can't reuse TFRecords since the training task is different and the TFRecords size is 10x the original text size due to duplication (dupe_factor).

But you can get access to the same data that we used from their sources which are mentioned in the Readme file.  You can then run our preprocessor on each line.

**Comment by WissamAntoun** [comment]
@ahmednasserswe can I close this issue? or there is something else you want to know?
