### ISSUE TITLE
Sentence embeddings for Arabic text

### ISSUE THREAD

**Issue by adeljalalyousif** [aub-mind/arabert#197]
Thank you for sharing your amazing work. I need to generate sentence embeddings for Arabic text, similar to the Multilingual Universal Sentence Encoder (MUSE). Can I achieve this with AraBERT or another version using PyTorch?
I need to check similarity  between two sentences, can you help me?

**Comment by WissamAntoun** [comment]
Hey, yes you can generate sentence embeddings with AraBERT, just like any other BERT model. But the thing is the quality of the sentence embeddings won't be the best, since the model is not trained to do that. 

This is a simple notebook that will help you start using it: https://colab.research.google.com/drive/1Xk8IGcwGTr-YNlB6lhl8jYdIU_M7Mcjx?usp=sharing

Also check the sentence transformers library if they have anything supported for arabic

**Comment by adeljalalyousif** [comment]
Thank you so mauch
