### ISSUE TITLE
Semantic Similarity Tasks

### ISSUE THREAD

**Issue by AlsalehAbdullah** [aub-mind/arabert#32]
Hello,

I'm trying to use your model to do semantic similarity tasks between Arabic sentences. Can you please guide me? 

Kind regards
Abdullah

**Comment by AlsalehAbdullah** [comment]
Sorry what I meant was, should I use the Bert model and import your tokenizer 

`AutoTokenizer.from_pretrained("aubmindlab/bert-base-arabert")`

instead of 

`transformers.BertTokenizer.from_pretrained("bert-base-uncased", do_lower_case=True)`

**Comment by WissamAntoun** [comment]
yes, just replace `bert-base-uncased` with `aubmindlab/bert-base-arabert` or `aubmindlab/bert-base-arabertv01`. You don't have to add `do_lower_case=True`

**Comment by AlsalehAbdullah** [comment]
Thank you for the quick reply.

I tried to see the token output of one sentence that I have using AraBert tokenizer

```
tokenizer = transformers.BertTokenizer.from_pretrained("aubmindlab/bert-base-arabert")
tokens = tokenizer.tokenize(df.loc[2, 'Verse_Text_Sim'])
print(tokens)
```

The output was:

`['[UNK]', 'يوم', 'ال', '##دي', '##ن']
`

The sentence/verse is from the Quran: "مالك يوم الدين"

So, is this normal with the hashes and the unknown token? If it's not normal, do you think there is an issue with my data in terms of font or type of string?

Thank you

**Comment by WissamAntoun** [comment]
I just tried it on "مالك يوم الدين" and it gave `['مالك', 'يوم', 'ال', '##دي', '##ن']`. 

The `##` is from the wordpiece tokenization since the word `الدين` doesn't exist in the vocabulary of AraBERTv1 (`aubmindlab/bert-base-arabert`). For AraBERTv1 you should apply pre segmentation before tokenization, check the example usage on the Readme file.

If you don't want to do pre-segmentation, you can try and use AraBERTv0.1 (`aubmindlab/bert-base-arabertv01`) instead, but you will still face the `##` issue.
