### ISSUE TITLE
 AraBERT_PyTorch_Demo.ipynb  for multi-class 

### ISSUE THREAD

**Issue by yassmine-lam** [aub-mind/arabert#38]
Hi,

I tried to use the notebook AraBERT_PyTorch_Demo.ipynb for a multi class classification problem
I ve changed the get_labels function to return my labels and also changed the num_labels in the Bert model
but I still got this error

![Screen Shot 2020-12-07 at 7 30 06 AM](https://user-images.githubusercontent.com/75603019/101317075-0f514e00-385e-11eb-8f57-6973522667e9.png)

could someone help plz!
Thank u

**Comment by WissamAntoun** [comment]
Hey,

It will be easier for you to try this notebook https://github.com/aub-mind/arabert/blob/master/examples/AraBERT_Text_Classification_with_HF_Trainer_Pytorch_GPU.ipynb

or the Fast-BERT Notebook since they both support multiclass.

If you want to fix this you need to do onehot encoding of the labels
