### ISSUE TITLE
is it SOTA 

### ISSUE THREAD

**Issue by salama4** [aub-mind/arabert#8]
i found another model, it trained on more data than you , but i couldn't argue which one is the state of the art ??
the other model i mind is [https://huggingface.co/asafaya/bert-base-arabic](url)

**Comment by WissamAntoun** [comment]
We haven't compared against asafaya/bert-base-arabic since it happened that we announced both models on the same day. Also looking at the https://github.com/alisafaya/Arabic-BERT repository you can see that results aren't yet posted.

Our main model uses pre-segmentation to improve on the "vanilla" approach and has achieved better results. While Asafaya's model was trained on more data, so don't know which will perform better until someone offers a direct comparison. ( If you did can you share with us the results?)
